export const BOLD = 'Montserrat-Bold'
export const SEMI_BOLD = 'Montserrat-SemiBold'
export const LIGHT = 'Montserrat-Light'
export const ITALIC = 'Montserrat-Italic'
export const MEDIUM = 'Montserrat-Medium'
export const REGULAR = 'Montserrat-Regular'